In [21]:
import matplotlib.pyplot as plt
import pcn_batch as pb
import pcn_sequential as ps
import numpy as np

import importlib

# reload the ps module to detect changes

importlib.reload(ps)

<module 'pcn_sequential' from '/Users/mderri/Desktop/MIU courses/Machine Learning Course/Labs/lab2/pcn_sequential.py'>

In [22]:
# Generate some data
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
targets = np.array([[0],[0],[0],[1]])

In [23]:
# Create the perceptron
p = pb.pcn(inputs,targets)
# Train with batch updates
p.pcntrain(inputs,targets,0.25,10)

Iteration:  0
[[0.21018875]
 [0.02600293]
 [0.01589329]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  1
[[-0.03981125]
 [-0.22399707]
 [ 0.51589329]]
Final outputs are:
[[0]
 [0]
 [0]
 [0]]
Iteration:  2
[[0.21018875]
 [0.02600293]
 [0.26589329]]
Final outputs are:
[[0]
 [0]
 [0]
 [0]]
Iteration:  3
[[0.46018875]
 [0.27600293]
 [0.01589329]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  4
[[0.21018875]
 [0.02600293]
 [0.51589329]]
Final outputs are:
[[0]
 [0]
 [0]
 [0]]
Iteration:  5
[[0.46018875]
 [0.27600293]
 [0.26589329]]
Final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  6
[[0.21018875]
 [0.02600293]
 [0.76589329]]
Final outputs are:
[[0]
 [0]
 [0]
 [0]]
Iteration:  7
[[0.46018875]
 [0.27600293]
 [0.51589329]]
Final outputs are:
[[0]
 [0]
 [0]
 [1]]
Iteration:  8
[[0.46018875]
 [0.27600293]
 [0.51589329]]
Final outputs are:
[[0]
 [0]
 [0]
 [1]]
Iteration:  9
[[0.46018875]
 [0.27600293]
 [0.51589329]]
Final outputs are:
[[0]
 [0]
 [0]
 [1]]


In [24]:
# Create a new perceptron
p2 = ps.pcn(inputs,targets)

# Train with sequential updates
p2.pcntrain(inputs,targets,0.25,40)

final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  1
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final output :  1
final output :  0
final output :  0
final output :  0
final outp